"$schema" = "https://starship.rs/config-schema.json"
format = """
$directory\
$git_branch\
$git_status\
$python\
$character\
"""
"add_newline" = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
home_symbol = "~"
truncation_length = 50
truncation_symbol = ".../"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[python]
format = "via [$virtualenv]($style) "
style = "yellow bold"
detect_extensions = []
detect_files = []

[git_branch]
symbol = " "
truncation_length = 4
truncation_symbol = ""
# ignore_branches = ['master', 'main']

[git_status]
style = "bold white"
conflicted = "="
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "*"
deleted = "-"
