[language-server.gopls]
command = "gopls"

[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true
"formatting.gofumpt" = true

[[language]]
name = "toml"
auto-format = true
language-servers = ["tombi"]

[[language]]
name = "go"
language-servers = ["gopls"]
auto-format = true
formatter = { command = "goimports" }
